### ISSUE TITLE
bug in document there is a chinese in english version of document https://www.rspack.dev/config/optimization.html

### ISSUE THREAD

**Issue by bronze1man** [web-infra-dev/blogs#11]
url : https://www.rspack.dev/config/optimization.html

<img width="356" alt="Screen Shot 2023-11-22 at 15 38 43" src="https://github.com/web-infra-dev/blogs/assets/1107541/79f66b16-eaf3-4d96-9a26-ae83e5bc18dc">

**Comment by hardfist** [comment]
thanks its fixed
